spring:
  application:
    name: springboot-develop
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true